name: nodelabscase
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # ** Utility **
  gap: ^3.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  easy_logger: ^0.0.2
  logger: ^2.4.0
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # ** Network Dependencies **
  dio: ^5.8.0+1
  http_parser: ^4.1.2

  # ** Core Dependencies **
  equatable: ^2.0.7
  shared_preferences: ^2.5.3

  # ** Navigation **
  auto_route: ^9.3.0

  # ** Config **
  easy_localization: ^3.0.7

  # ** State **
  flutter_bloc: ^9.1.1

  # ** Private Packages **
  common:
    path: module/common

  gen:
    path: module/gen

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#485D92"
  image: module/gen/assets/images/lawai.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
